services:

  apache:
    build:
      context: ./apache
    container_name: multidomain-apache
    ports:
      - "80:80"
    volumes:
      - ./sites:/var/www/sites
      - ./shared:/var/www/shared
    depends_on:
      - php
    networks:
      - web

  php:
    image: php:8.5-fpm
    container_name: multidomain-php
    volumes:
      - ./sites:/var/www/sites
      - ./shared:/var/www/shared
    networks:
      - web

networks:
  web: